image:
  repository: thangvu201098/reaktor
  tag: latest
  pullPolicy: IfNotPresent
ingress:
  host: reaktor-web.192.168.49.2.nip.io
env:
  API_URL: http://reaktor-api.192.168.49.2.nip.io
service:
  name: reaktor
  type: ClusterIP
  internalPort: 80
  externalPort: 80
