image:
  repository: thangvu201098/reaktor-web
  tag: 0.0.4
  pullPolicy: IfNotPresent
ingress:
  host: reaktor-web.vvthang.com
  path: /
env:
  API_URL: http://reaktor-api.vvthang.com
service:
  name: reaktor-web
  type: ClusterIP
  internalPort: 80
  externalPort: 80

