image:
  repository: thangvu201098/reaktor
  tag: latest
  pullPolicy: IfNotPresent
ingress:
  host: reaktor-web.192.168.49.2.nip.io
  path: /
env:
  API_URL: http://aeb8b626b54e042208a30db17d483073-f22a1c54c3a4d00b.elb.eu-west-1.amazonaws.com/api
service:
  name: reaktor
  type: ClusterIP
  internalPort: 80
  externalPort: 80
