image:
  repository: thangvu201098/reaktor-web
  tag: 0.0.4
  pullPolicy: IfNotPresent
ingress:
  path: /
env:
  API_URL: http://aeb8b626b54e042208a30db17d483073-f22a1c54c3a4d00b.elb.eu-west-1.amazonaws.com/api
service:
  name: reaktor-web
  type: ClusterIP
  internalPort: 80
  externalPort: 80
